services:
  - type: web
    name: shiksha-sathi
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY2
        sync: false
      - key: SARVAM_API_KEY
        sync: false
